name: pre-commit
on: pull_request
permissions:
  contents: read

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.13'

      - uses: actions/setup-java@v6
        with:
          java-version-file: .java-version
          distribution: temurin

      - name: Cache pre-commit envs
        uses: actions/cache@v6
        with:
          path: ~/.cache/pre-commit
          key: pre-commit|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Run pre-commit
        run: |
          python -m pip install pre-commit
          pre-commit run --show-diff-on-failure --color=always --from-ref=${{ github.event.pull_request.base.sha }} --to-ref=${{ github.sha }}
